import * as XLSX from "xlsx";

const getDocumentName = (filePath) => {
  const normalizedPath = String(filePath || "").replace(/\\/g, "/").trim();
  if (!normalizedPath) return "---";

  return normalizedPath.split("/").pop() || normalizedPath;
};

const hasNumberValue = (value) =>
  value !== undefined && value !== null && value !== "";

const buildSummary = (products = [], summary = {}) => {
  const rowTotals = products.reduce(
    (totals, product) => {
      const amount = Number(product.amount || 0);
      const paymentStatus = String(product.paymentStatus || "").toLowerCase();

      if (paymentStatus === "cashin") totals.cashIn += amount;
      if (paymentStatus === "cashout") totals.cashOut += amount;

      return totals;
    },
    { cashIn: 0, cashOut: 0 },
  );

  const cashIn = hasNumberValue(summary.totalCashIn)
    ? Number(summary.totalCashIn || 0)
    : rowTotals.cashIn;
  const cashOut = hasNumberValue(summary.totalCashOut)
    ? Number(summary.totalCashOut || 0)
    : rowTotals.cashOut;
  const finalBalance = hasNumberValue(summary.netBalance)
    ? Number(summary.netBalance || 0)
    : cashIn - cashOut;

  return { cashIn, cashOut, finalBalance };
};

const formatAmount = (value) => Number(value || 0).toFixed(2);

const normalizeReportMeta = (metadata = {}) => ({
  duration: metadata.duration || "All Data",
  generatedBy: metadata.generatedBy || "Unknown",
  generatedAt: metadata.generatedAt || new Date().toLocaleString(),
});

export const generateCashInOutXlsx = ({
  products = [],
  bookId = "",
  bookName = "",
  summary = {},
  metadata = {},
}) => {
  // ✅ Title
  const title = bookName ? `Report: ${bookName}` : "Cash In/Out Report";
  const reportSummary = buildSummary(products, summary);
  const reportMetadata = normalizeReportMeta(metadata);

  // Header + rows
  const header = [
    "Date",
    "Document",
    "Category",
    "Payment Mode",
    "Remarks",
    "CashIn",
    "CashOut",
  ];

  // const fmtDate = (d) => {
  //   if (!d) return "-";
  //   const dt = new Date(d);
  //   if (Number.isNaN(dt.getTime())) return "-";
  //   return dt.toLocaleDateString();
  // };

  const rows = products.map((p) => {
    const amount = Number(p.amount || 0).toFixed(2);
    const paymentStatus = String(p.paymentStatus || "").toLowerCase();

    return [
      // fmtDate(p.date),
      p.date,
      getDocumentName(p.file),
      p.categoryInfo?.name || p.category || "---",
      p.paymentMode || "-",
      p.remarks || "-",
      paymentStatus === "cashin" ? amount : "",
      paymentStatus === "cashout" ? amount : "",
    ];
  });

  const aoa = [
    [title],
    [`BookId: ${bookId || "-"}`],
    [`Total Rows: ${products.length}`],
    [
      `Duration: ${reportMetadata.duration}`,
      `Generated by: ${reportMetadata.generatedBy}`,
      `Generated on: ${reportMetadata.generatedAt}`,
    ],
    [],
    ["Total Cash In", "Total Cash Out", "Final Balance"],
    [
      formatAmount(reportSummary.cashIn),
      formatAmount(reportSummary.cashOut),
      formatAmount(reportSummary.finalBalance),
    ],
    [],
    header,
    ...rows,
  ];

  const ws = XLSX.utils.aoa_to_sheet(aoa);

  // ✅ Merge title across columns
  ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: header.length - 1 } }];

  // ✅ column width
  ws["!cols"] = [
    { wch: 14 }, // Date
    { wch: 20 }, // Document
    { wch: 18 }, // Category
    { wch: 16 }, // Payment Mode
    { wch: 45 }, // Remarks
    { wch: 14 }, // CashIn
    { wch: 14 }, // CashOut
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "CashInOut");

  // ArrayBuffer -> Blob
  const arrayBuffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  const blob = new Blob([arrayBuffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  // Preview data (React table এ দেখানোর জন্য)
  return {
    blob,
    preview: {
      title, // ✅ চাইলে modal এ উপরে দেখাতে পারবে
      summary: reportSummary,
      metadata: reportMetadata,
      header,
      rows,
    },
  };
};
