export const REPORT_GROUPS = {
  assets: { key: "assets", label: "Assets" },
  marketing: { key: "marketing", label: "Marketing" },
  packaging: { key: "packaging", label: "Packaging" },
  manufacture: { key: "manufacture", label: "Manufacture" },
  inventory: { key: "inventory", label: "Inventory Reports" },
  damage_management: { key: "damage_management", label: "Damage Management" },
  pos_panel: { key: "pos_panel", label: "POS" },
  accounting: { key: "accounting", label: "Accounting" },
  hrm: { key: "hrm", label: "HRM" },
  hr_payroll: { key: "hr_payroll", label: "Payroll" },
  shifa: { key: "shifa", label: "Shifa" },
  system: { key: "system", label: "System" },
};

export const REPORT_CATALOG = [
  { key: "inventory-reports", label: "Inventory Reports", groupKey: "inventory", endpoint: "/inventory/reports", searchParam: "name", startDateParam: "from", endDateParam: "to" },
  { key: "products", label: "Products", groupKey: "inventory", endpoint: "/product", searchParam: "name" },
  { key: "inventory-overview", label: "Inventory Overview", groupKey: "inventory", endpoint: "/inventory/list", searchParam: "name", startDateParam: "from", endDateParam: "to" },
  { key: "stock-product", label: "Stock Product", groupKey: "inventory", endpoint: "/inventory-master", searchParam: "name" },
  { key: "stock-alert", label: "Stock Alert", groupKey: "inventory", endpoint: "/inventory-master/low-stock", searchParam: "name" },
  { key: "warehouse", label: "Warehouse", groupKey: "inventory", endpoint: "/warehouse", searchParam: "searchTerm" },
  { key: "supplier", label: "Supplier", groupKey: "inventory", endpoint: "/supplier", searchParam: "searchTerm" },
  { key: "received-product", label: "Purchase Product", groupKey: "inventory", endpoint: "/received-product", searchParam: "searchTerm" },
  { key: "intransit-product", label: "In Transit Product", groupKey: "inventory", endpoint: "/intransit-product", searchParam: "searchTerm" },
  { key: "courier-no-entry", label: "Courier No Entry", groupKey: "inventory", endpoint: "/courier-no-entry", searchParam: "searchTerm" },
  { key: "sales-return", label: "Sales Return", groupKey: "inventory", endpoint: "/return-product", searchParam: "searchTerm" },
  { key: "purchase-return", label: "Purchase Return", groupKey: "inventory", endpoint: "/purchase-return-product", searchParam: "searchTerm" },
  { key: "confirm-order", label: "Confirm Order", groupKey: "pos_panel", endpoint: "/confirm-order", searchParam: "searchTerm" },
  { key: "pos-report", label: "POS Report", groupKey: "pos_panel", endpoint: "/pos-report", searchParam: "searchTerm" },
  { key: "assets-stock", label: "Assets Stock", groupKey: "assets", endpoint: "/assets-stock", searchParam: "name" },
  { key: "assets-requisition", label: "Assets Requisition", groupKey: "assets", endpoint: "/assets-requisition", searchParam: "searchTerm" },
  { key: "assets-purchase", label: "Assets Purchase", groupKey: "assets", endpoint: "/assets-purchase", searchParam: "name" },
  { key: "assets-sale", label: "Assets Sale", groupKey: "assets", endpoint: "/assets-sale", searchParam: "name" },
  { key: "assets-damage", label: "Assets Damage", groupKey: "assets", endpoint: "/assets-damage", searchParam: "name" },
  { key: "damage-stock", label: "Damage Stock", groupKey: "damage_management", endpoint: "/damage-stock", searchParam: "name" },
  { key: "damage-product", label: "Damage Product", groupKey: "damage_management", endpoint: "/damage-product", searchParam: "name" },
  { key: "damage-repairing-stock", label: "Damage Repairing Stock", groupKey: "damage_management", endpoint: "/damage-repairing-stock", searchParam: "name" },
  { key: "damage-repair", label: "Damage Repair", groupKey: "damage_management", endpoint: "/damage-repair", searchParam: "name" },
  { key: "damage-repaired", label: "Damage Repaired", groupKey: "damage_management", endpoint: "/damage-repaired", searchParam: "name" },
  { key: "meta-expense", label: "Meta Expense", groupKey: "marketing", endpoint: "/meta", searchParam: "searchTerm", extraParams: { platform: "Meta" } },
  { key: "google-expense", label: "Google Expense", groupKey: "marketing", endpoint: "/meta", searchParam: "searchTerm", extraParams: { platform: "Google" } },
  { key: "tiktok-expense", label: "Tiktok Expense", groupKey: "marketing", endpoint: "/meta", searchParam: "searchTerm", extraParams: { platform: "Tiktok" } },
  { key: "seo-expense", label: "SEO Expense", groupKey: "marketing", endpoint: "/meta", searchParam: "searchTerm", extraParams: { platform: "SEO" } },
  { key: "marketing-book", label: "Marketing Book", groupKey: "marketing", endpoint: "/marketing-book", searchParam: "searchTerm" },
  { key: "marketing-expense", label: "Marketing Expense", groupKey: "marketing", endpoint: "/marketing-expense", searchParam: "searchTerm" },
  { key: "ads-campaign-kpi", label: "Ads Campaign KPI", groupKey: "marketing", endpoint: "/ads-campaign-kpi", searchParam: "searchTerm" },
  { key: "profit-loss", label: "Daily Profit & Loss By Product", groupKey: "marketing", endpoint: "/profit-loss", searchParam: "searchTerm" },
  { key: "profit-loss-user", label: "Daily Profit & Loss By User", groupKey: "marketing", endpoint: "/profit-loss/user", searchParam: "searchTerm" },
  { key: "book", label: "Accounting Book", groupKey: "accounting", endpoint: "/book", searchParam: "searchTerm" },
  { key: "cash-in-out", label: "Cash In/Out", groupKey: "accounting", endpoint: "/cash-in-out", searchParam: "searchTerm" },
  { key: "expense", label: "Expense", groupKey: "accounting", endpoint: "/expense", searchParam: "name" },
  { key: "petty-cash", label: "Petty Cash", groupKey: "accounting", endpoint: "/petty-cash", searchParam: "searchTerm" },
  { key: "petty-cash-requisition", label: "Petty Cash Requisition", groupKey: "accounting", endpoint: "/petty-cash-requisition", searchParam: "searchTerm" },
  { key: "loan", label: "Loan", groupKey: "accounting", endpoint: "/loan", searchParam: "searchTerm" },
  { key: "owner", label: "Owner", groupKey: "accounting", endpoint: "/owner", searchParam: "searchTerm" },
  { key: "owner-transaction", label: "Owner Transaction", groupKey: "accounting", endpoint: "/owner-transaction", searchParam: "searchTerm" },
  { key: "credit-ledger", label: "Credit Ledger", groupKey: "accounting", endpoint: "/ledger", searchParam: "searchTerm" },
  { key: "payable", label: "Payable", groupKey: "accounting", endpoint: "/payable", searchParam: "searchTerm" },
  { key: "receivable", label: "Receivable", groupKey: "accounting", endpoint: "/receiveable", searchParam: "searchTerm" },
  { key: "packaging-item", label: "Packaging Item", groupKey: "packaging", endpoint: "/packaging-item", searchParam: "searchTerm" },
  { key: "packaging-item-stock", label: "Packaging Item Stock", groupKey: "packaging", endpoint: "/packaging-item-stock", searchParam: "searchTerm" },
  { key: "packaging-item-purchase", label: "Packaging Item Purchase", groupKey: "packaging", endpoint: "/packaging-item-purchase", searchParam: "searchTerm" },
  { key: "packaging-manufacturer", label: "Packaging Manufacturer", groupKey: "packaging", endpoint: "/packaging-manufacturer", searchParam: "searchTerm" },
  { key: "packaging-factory", label: "Packaging Factory", groupKey: "packaging", endpoint: "/packaging-factory", searchParam: "searchTerm" },
  { key: "packaging-factory-stock", label: "Packaging Factory Stock", groupKey: "packaging", endpoint: "/packaging-factory-stock", searchParam: "searchTerm" },
  { key: "packaging-mixer", label: "Packaging Mixer", groupKey: "packaging", endpoint: "/packaging-mixer", searchParam: "searchTerm" },
  { key: "item", label: "Item", groupKey: "manufacture", endpoint: "/item", searchParam: "name" },
  { key: "item-requisition", label: "Item Requisition", groupKey: "manufacture", endpoint: "/item-requisition", searchParam: "searchTerm" },
  { key: "item-stock", label: "Item Stock", groupKey: "manufacture", endpoint: "/item-master", searchParam: "name" },
  { key: "item-purchase", label: "Item Purchase", groupKey: "manufacture", endpoint: "/item-purchase", searchParam: "name" },
  { key: "manufacturer", label: "Manufacturer", groupKey: "manufacture", endpoint: "/manufacturer", searchParam: "searchTerm" },
  { key: "manufacture-stock", label: "Manufacture Stock", groupKey: "manufacture", endpoint: "/manufacture-stock", searchParam: "name" },
  { key: "manufacture", label: "Manufacture", groupKey: "manufacture", endpoint: "/manufacture", searchParam: "searchTerm" },
  { key: "stock-adjustment", label: "Stock Adjustment", groupKey: "manufacture", endpoint: "/stock-adjustment", searchParam: "searchTerm" },
  { key: "stock-movement", label: "Stock Movement", groupKey: "manufacture", endpoint: "/stock-movement", searchParam: "searchTerm" },
  { key: "mixer", label: "Mixer", groupKey: "manufacture", endpoint: "/mixer", searchParam: "searchTerm" },
  { key: "employee-list", label: "Employee List", groupKey: "hr_payroll", endpoint: "/employee-list", searchParam: "searchTerm" },
  { key: "employee", label: "Employee", groupKey: "hrm", endpoint: "/employee", searchParam: "searchTerm" },
  { key: "user-management", label: "User Management", groupKey: "system", endpoint: "/user", searchParam: "searchTerm" },
  { key: "employee-kpi", label: "Employee KPI", groupKey: "hr_payroll", endpoint: "/kpi", searchParam: "searchTerm" },
  { key: "salary", label: "Salary", groupKey: "hr_payroll", endpoint: "/salary", searchParam: "searchTerm" },
  { key: "departments", label: "Departments", groupKey: "hrm", endpoint: "/department", searchParam: "searchTerm" },
  { key: "designations", label: "Designations", groupKey: "hrm", endpoint: "/designation", searchParam: "searchTerm" },
  { key: "teams", label: "Teams", groupKey: "hrm", endpoint: "/team", searchParam: "searchTerm" },
  { key: "daily-work-reports", label: "Daily Work Reports", groupKey: "hrm", endpoint: "/daily-work-reports", searchParam: "searchTerm" },
  { key: "employee-work-reports", label: "Employee Work Reports", groupKey: "hrm", endpoint: "/employee-work-reports", searchParam: "searchTerm" },
  { key: "logistic-work-reports", label: "Logistic Work Reports", groupKey: "hrm", endpoint: "/logistic-work-reports", searchParam: "searchTerm" },
  { key: "logistic-updates", label: "Logistic Updates", groupKey: "hrm", endpoint: "/logistic-updates", searchParam: "searchTerm" },
  { key: "log-history", label: "Log History", groupKey: "system", endpoint: "/user-log-history", searchParam: "searchTerm" },
  { key: "shifa-call-history", label: "Shifa Call History", groupKey: "shifa", endpoint: "/shifa-reports", searchParam: "searchTerm", extraParams: { reportType: "call_history" } },
  { key: "shifa-starting-situation", label: "Shifa Starting Situation", groupKey: "shifa", endpoint: "/shifa-reports", searchParam: "searchTerm", extraParams: { reportType: "starting_situation" } },
  { key: "shifa-problem-history", label: "Shifa Problem History", groupKey: "shifa", endpoint: "/shifa-reports", searchParam: "searchTerm", extraParams: { reportType: "problem_history" } },
  { key: "shifa-patient-update", label: "Shifa Patient Update", groupKey: "shifa", endpoint: "/shifa-reports", searchParam: "searchTerm", extraParams: { reportType: "patient_update" } },
];

export const REPORT_PERMISSION_KEYS = REPORT_CATALOG.map(
  (report) => `report_${report.key.replaceAll("-", "_")}`,
);

export const getReportByKey = (key) =>
  REPORT_CATALOG.find((report) => report.key === key) || REPORT_CATALOG[0];

export const getReportGroupByKey = (key) => REPORT_GROUPS[key] || null;

export const getReportsByGroup = (groupKey) =>
  groupKey
    ? REPORT_CATALOG.filter((report) => report.groupKey === groupKey)
    : REPORT_CATALOG;
