export const REPORT_CATALOG = [
  { key: "products", label: "Products", endpoint: "/product", searchParam: "name" },
  { key: "inventory-overview", label: "Inventory Overview", endpoint: "/inventory/list", searchParam: "name", startDateParam: "from", endDateParam: "to" },
  { key: "stock-product", label: "Stock Product", endpoint: "/inventory-master", searchParam: "name" },
  { key: "stock-alert", label: "Stock Alert", endpoint: "/inventory-master/low-stock", searchParam: "name" },
  { key: "warehouse", label: "Warehouse", endpoint: "/warehouse", searchParam: "searchTerm" },
  { key: "supplier", label: "Supplier", endpoint: "/supplier", searchParam: "searchTerm" },
  { key: "received-product", label: "Purchase Product", endpoint: "/received-product", searchParam: "searchTerm" },
  { key: "intransit-product", label: "In Transit Product", endpoint: "/intransit-product", searchParam: "searchTerm" },
  { key: "courier-no-entry", label: "Courier No Entry", endpoint: "/courier-no-entry", searchParam: "searchTerm" },
  { key: "sales-return", label: "Sales Return", endpoint: "/return-product", searchParam: "searchTerm" },
  { key: "purchase-return", label: "Purchase Return", endpoint: "/purchase-return-product", searchParam: "searchTerm" },
  { key: "confirm-order", label: "Confirm Order", endpoint: "/confirm-order", searchParam: "searchTerm" },
  { key: "pos-report", label: "POS Report", endpoint: "/pos-report", searchParam: "searchTerm" },
  { key: "assets-stock", label: "Assets Stock", endpoint: "/assets-stock", searchParam: "name" },
  { key: "assets-requisition", label: "Assets Requisition", endpoint: "/assets-requisition", searchParam: "searchTerm" },
  { key: "assets-purchase", label: "Assets Purchase", endpoint: "/assets-purchase", searchParam: "name" },
  { key: "assets-sale", label: "Assets Sale", endpoint: "/assets-sale", searchParam: "name" },
  { key: "assets-damage", label: "Assets Damage", endpoint: "/assets-damage", searchParam: "name" },
  { key: "damage-stock", label: "Damage Stock", endpoint: "/damage-stock", searchParam: "name" },
  { key: "damage-product", label: "Damage Product", endpoint: "/damage-product", searchParam: "name" },
  { key: "damage-repairing-stock", label: "Damage Repairing Stock", endpoint: "/damage-repairing-stock", searchParam: "name" },
  { key: "damage-repair", label: "Damage Repair", endpoint: "/damage-repair", searchParam: "name" },
  { key: "damage-repaired", label: "Damage Repaired", endpoint: "/damage-repaired", searchParam: "name" },
  { key: "meta-expense", label: "Meta Expense", endpoint: "/meta", searchParam: "searchTerm", extraParams: { platform: "Meta" } },
  { key: "google-expense", label: "Google Expense", endpoint: "/meta", searchParam: "searchTerm", extraParams: { platform: "Google" } },
  { key: "tiktok-expense", label: "Tiktok Expense", endpoint: "/meta", searchParam: "searchTerm", extraParams: { platform: "Tiktok" } },
  { key: "seo-expense", label: "SEO Expense", endpoint: "/meta", searchParam: "searchTerm", extraParams: { platform: "SEO" } },
  { key: "marketing-book", label: "Marketing Book", endpoint: "/marketing-book", searchParam: "searchTerm" },
  { key: "marketing-expense", label: "Marketing Expense", endpoint: "/marketing-expense", searchParam: "searchTerm" },
  { key: "ads-campaign-kpi", label: "Ads Campaign KPI", endpoint: "/ads-campaign-kpi", searchParam: "searchTerm" },
  { key: "profit-loss", label: "Daily Profit & Loss By Product", endpoint: "/profit-loss", searchParam: "searchTerm" },
  { key: "profit-loss-user", label: "Daily Profit & Loss By User", endpoint: "/profit-loss/user", searchParam: "searchTerm" },
  { key: "book", label: "Accounting Book", endpoint: "/book", searchParam: "searchTerm" },
  { key: "cash-in-out", label: "Cash In/Out", endpoint: "/cash-in-out", searchParam: "searchTerm" },
  { key: "expense", label: "Expense", endpoint: "/expense", searchParam: "name" },
  { key: "petty-cash", label: "Petty Cash", endpoint: "/petty-cash", searchParam: "searchTerm" },
  { key: "petty-cash-requisition", label: "Petty Cash Requisition", endpoint: "/petty-cash-requisition", searchParam: "searchTerm" },
  { key: "loan", label: "Loan", endpoint: "/loan", searchParam: "searchTerm" },
  { key: "owner", label: "Owner", endpoint: "/owner", searchParam: "searchTerm" },
  { key: "owner-transaction", label: "Owner Transaction", endpoint: "/owner-transaction", searchParam: "searchTerm" },
  { key: "credit-ledger", label: "Credit Ledger", endpoint: "/ledger", searchParam: "searchTerm" },
  { key: "payable", label: "Payable", endpoint: "/payable", searchParam: "searchTerm" },
  { key: "receivable", label: "Receivable", endpoint: "/receiveable", searchParam: "searchTerm" },
  { key: "packaging-item", label: "Packaging Item", endpoint: "/packaging-item", searchParam: "searchTerm" },
  { key: "packaging-item-stock", label: "Packaging Item Stock", endpoint: "/packaging-item-stock", searchParam: "searchTerm" },
  { key: "packaging-item-purchase", label: "Packaging Item Purchase", endpoint: "/packaging-item-purchase", searchParam: "searchTerm" },
  { key: "packaging-manufacturer", label: "Packaging Manufacturer", endpoint: "/packaging-manufacturer", searchParam: "searchTerm" },
  { key: "packaging-factory", label: "Packaging Factory", endpoint: "/packaging-factory", searchParam: "searchTerm" },
  { key: "packaging-factory-stock", label: "Packaging Factory Stock", endpoint: "/packaging-factory-stock", searchParam: "searchTerm" },
  { key: "packaging-mixer", label: "Packaging Mixer", endpoint: "/packaging-mixer", searchParam: "searchTerm" },
  { key: "item", label: "Item", endpoint: "/item", searchParam: "name" },
  { key: "item-requisition", label: "Item Requisition", endpoint: "/item-requisition", searchParam: "searchTerm" },
  { key: "item-stock", label: "Item Stock", endpoint: "/item-master", searchParam: "name" },
  { key: "item-purchase", label: "Item Purchase", endpoint: "/item-purchase", searchParam: "name" },
  { key: "manufacturer", label: "Manufacturer", endpoint: "/manufacturer", searchParam: "searchTerm" },
  { key: "manufacture-stock", label: "Manufacture Stock", endpoint: "/manufacture-stock", searchParam: "name" },
  { key: "manufacture", label: "Manufacture", endpoint: "/manufacture", searchParam: "searchTerm" },
  { key: "stock-adjustment", label: "Stock Adjustment", endpoint: "/stock-adjustment", searchParam: "searchTerm" },
  { key: "stock-movement", label: "Stock Movement", endpoint: "/stock-movement", searchParam: "searchTerm" },
  { key: "mixer", label: "Mixer", endpoint: "/mixer", searchParam: "searchTerm" },
  { key: "employee-list", label: "Employee List", endpoint: "/employee-list", searchParam: "searchTerm" },
  { key: "employee", label: "Employee", endpoint: "/employee", searchParam: "searchTerm" },
  { key: "user-management", label: "User Management", endpoint: "/user", searchParam: "searchTerm" },
  { key: "employee-kpi", label: "Employee KPI", endpoint: "/kpi", searchParam: "searchTerm" },
  { key: "salary", label: "Salary", endpoint: "/salary", searchParam: "searchTerm" },
  { key: "departments", label: "Departments", endpoint: "/department", searchParam: "searchTerm" },
  { key: "designations", label: "Designations", endpoint: "/designation", searchParam: "searchTerm" },
  { key: "teams", label: "Teams", endpoint: "/team", searchParam: "searchTerm" },
  { key: "daily-work-reports", label: "Daily Work Reports", endpoint: "/daily-work-reports", searchParam: "searchTerm" },
  { key: "employee-work-reports", label: "Employee Work Reports", endpoint: "/employee-work-reports", searchParam: "searchTerm" },
  { key: "logistic-work-reports", label: "Logistic Work Reports", endpoint: "/logistic-work-reports", searchParam: "searchTerm" },
  { key: "logistic-updates", label: "Logistic Updates", endpoint: "/logistic-updates", searchParam: "searchTerm" },
  { key: "log-history", label: "Log History", endpoint: "/user-log-history", searchParam: "searchTerm" },
  { key: "shifa-call-history", label: "Shifa Call History", endpoint: "/shifa-reports", searchParam: "searchTerm", extraParams: { reportType: "call_history" } },
  { key: "shifa-starting-situation", label: "Shifa Starting Situation", endpoint: "/shifa-reports", searchParam: "searchTerm", extraParams: { reportType: "starting_situation" } },
  { key: "shifa-problem-history", label: "Shifa Problem History", endpoint: "/shifa-reports", searchParam: "searchTerm", extraParams: { reportType: "problem_history" } },
  { key: "shifa-patient-update", label: "Shifa Patient Update", endpoint: "/shifa-reports", searchParam: "searchTerm", extraParams: { reportType: "patient_update" } },
];

export const REPORT_PERMISSION_KEYS = REPORT_CATALOG.map(
  (report) => `report_${report.key.replaceAll("-", "_")}`,
);

export const getReportByKey = (key) =>
  REPORT_CATALOG.find((report) => report.key === key) || REPORT_CATALOG[0];
